version: "3.7"

services:
  backend:
    container_name: todo-backend
    image: golang:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./backend:/server/app
      - storage_backend:/server/storage
    command: sh -c 'cd /server/app && go mod download && go run main.go'
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"     # provisional based on default port of Revel, should later be changed to what we intended to use

  frontend:
    container_name: todo-frontend
    image: node:12
    restart: unless-stopped
    volumes:
        - ./frontend:/server/frontend
    command: sh -c 'cd /server/frontend && yarn && yarn serve'
    ports:
      - "8080:8080"

  redis:
    container_name: todo-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - storage_redis:/data

volumes:
  storage_backend:
  storage_redis:
