version: "3.7"

services:
  backend:
    container_name: todo-backend
    image: golang:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./backend:/server/backend
    working_dir: /server/backend
    command: sh -c 'go mod download && go run main.go'
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"

  frontend:
    container_name: todo-frontend
    image: node:12
    restart: unless-stopped
    volumes:
      - ./frontend:/server/frontend
    working_dir: /server/frontend
    command: sh -c 'yarn && yarn serve'
    ports:
      - "8080:8080"

  redis:
    container_name: todo-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - storage_redis:/data

volumes:
  storage_redis:
