version: "3.7"

services:
  backend:
    container_name: todo-backend
    image: node:12
    restart: unless-stopped
    volumes:
      - ./backend:/server/app
      - storage_backend:/server/storage
    command: sh -c 'cd /server/app && yarn && yarn start:dev'
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    container_name: todo-frontend
    image: node:12
    restart: unless-stopped
    volumes:
        - ./frontend:/server/frontend
    command: sh -c 'cd /server/frontend && yarn && yarn serve'
    ports:
      - "8080:8080"

  redis:
    container_name: todo-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - storage_redis:/data

volumes:
  storage_backend:
  storage_redis:
