version: "3.7"

services:
  api:
    container_name: scrumble-api
    image: node:12
    restart: unless-stopped
    volumes:
      - .:/server/app
      - storage:/server/storage
    command: sh -c 'cd /server && yarn && yarn start:dev'
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  storage:
